### ISSUE TITLE
Does it run on Armbian legacy kernel.

### ISSUE THREAD

**Issue by asakous** [mosajjal/r6p2#2]
possible compile it on armbian kernel 3.4.x ?

**Comment by mosajjal** [comment]
In theory, yes. I haven't tested it personally on legacy kernel but there's no reason it won't work. Although I've specifically asked for mainline drivers and they gave me this one.

**Comment by asakous** [comment]
@mosajjal  thanks . I will test it sometime next month .

**Comment by mosajjal** [comment]
cool! Please share your experience when it's done :-)

**Comment by asakous** [comment]
mali.ko compiled . but fail to modprobe.  it can be insert module by using  --force parameter. unfortunately when I launch Retroarch it crashed.

**Comment by mosajjal** [comment]
I think you should have 3 `.ko` files. insert them in the right order and you'll have it. Better to put them inside `xorg` config because they have to be loaded before xorg

**Comment by asakous** [comment]
@mosajjal I run Retroarch  in framebuffer mode . so I only need 2 ko files. one is mali.ko another is ump.ko.
because of MODVERSIONS . so I can't build the right version of kernel module for my system. To solve my problem I need to recompile kernel and modules . that's too much to me. sorry for the bad result.

**Comment by mosajjal** [comment]
Too bad. Although I think you can download `armbian` and use their kernel and modules for RetroArch. Armbain comes with good performance drivers already shipped with it. Good luck :-)
