### ISSUE TITLE
How to load the Mali GPU device driver?

### ISSUE THREAD

**Issue by troyane** [mosajjal/r6p2#3]
There is first step in original readme `Load the Mali GPU device driver`. But how is it possible to do for example on mainline kernel 4.14 on H3 board with Armbian? `modprobe mali` say that there is no such module. In case if such module should be build by hands, could you please share any useful documentation/links, please?

Thanks.

**Comment by AbiuPlayer** [comment]
Sorry but only in Italian.
See this guide for both kernel and userspace drivers

http://abiuplayer.altervista.org/compilare-i-drivers-kernel-e-userspace-per-gpu-mali-su-allwinner-h3-e-h5/
